### ISSUE TITLE
Readme file completely doesn't understand

### ISSUE THREAD

**Issue by shuiyihan12** [Mirantis/cri-dockerd#195] opened 2023-06-02 08:53 UTC
Hello, as a beginner of Kubernetes, when installing Kubernetes, I learned that it is necessary to use cri docked to be compatible with Kubelet and docker. But your document is really difficult to understand. I don't think it's a language issue, and I don't know what to do with this project. Use the git clone project to directly compile and run it? What does Kubelet need to consider? Where does the docker need to be modified? Oh, my goodness

**Comment by afbjorklund** [comment] 2023-06-02 09:51
There is no end-user documentation here, and there are some bugs in the developer documentation as well.

* #154

The best thing meanwhile, would be to look at the [k8s.io documentation](https://kubernetes.io/docs/setup/production-environment/container-runtimes/) and under "Releases" for the packages:

https://github.com/Mirantis/cri-dockerd/releases

**Comment by neersighted** [comment] 2023-06-02 11:49
@nwneisen Can you close this as a duplicate of #154 please?

**Closed** 2023-06-05 19:05 UTC
